name: Enrichir catalogue livres

on:
  push:
    paths:
      - 'books.json'
      - 'enrich_books.mjs'
      - '.github/workflows/enrich-catalogue.yml'
      - 'generate_sitemap.mjs'
  workflow_dispatch:

jobs:
  enrich:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Lancer enrich_books.mjs
        run: node enrich_books.mjs

      - name: Commit et push si modifié
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add books.json sitemap.xml || true
          git diff --cached --quiet || git commit -m "Mise à jour automatique du catalogue"
          git push
